# Site settings
# These are used to personalize your site. You access them via {{ site.title }}, 
# {{ site.email }} and so on. You can create any custom variable you like. They
# will be accessible in the templates via {{ site.myvariable }}.

title: License
email: info@getlicensekit.com
description: >-
  LicenseKit helps you protect your Swift-based apps and libraries with a commercial license.

url: http://getlicensekit.com
rss_url: https://getlicensekit.com/feed.xml
is_lib: 1

copyright_year: 2022-2023
copyright_owner: Kankoda Sweden AB
copyright_url: https://kankoda.com

documentation_url: https://licensekit.github.io/LicenseKit/documentation/licensekit/
github_url: https://github.com/LicenseKit/LicenseKit
github_username: LicenseKit
gumroad_url: https://danielsaidi.gumroad.com
gumroad_url_basic: https://danielsaidi.gumroad.com/l/licensekit-basic
gumroad_url_gold: https://danielsaidi.gumroad.com/l/licensekit-gold
mastodon_url: https://techhub.social/@licensekit
mastodon_username: licensekit@techhub.social
twitter_url: https://twitter.com/getlicensekit
twitter_username: getlicensekit

assets: /assets/
header_image: /assets/icon/icon-header.png
header_image_type: icon

header_pages:
  - index.html
  - pages/blog.md
  - pages/pricing.md

footer_sitemap:
  - index.html
  - pages/blog.md
  - pages/pricing.md

collections_dir: collections

collections:
  posts:
    output: true
    permalink: /blog/:categories/:year/:month/:day/:title
  sponsors:
    output: true
    permalink: /sponsor/:name/

baseurl: ""
theme: minima
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-redirect-from

defaults:
  -
    scope:
      type: "pages"
    values:
      hero: ""
  -
    scope:
      type: "posts"
    values:
      author: "danielsaidi"
      layout: "post"
      hero:   ""
  -
    scope:
      type: "sponsors"
    values:
      layout: "sponsor"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/