# Site settings
# These are used to personalize your site. You access them via {{ site.title }}, 
# {{ site.email }} and so on. You can create any custom variable you like. They
# will be accessible in the templates via {{ site.myvariable }}.

title: License
email: info@getlicensekit.com
description: >-
  LicenseKit helps you protect your Swift-based apps and libraries with a commercial license.

url: http://getlicensekit.com

copyright_year: 2022
copyright_owner: Kankoda Sweden AB
copyright_url: https://kankoda.com

github: https://github.com/LicenseKit
github_repo: https://github.com/LicenseKit/LicenseKit
github_username: LicenseKit
gumroad: https://danielsaidi.gumroad.com
gumroad-basic: https://danielsaidi.gumroad.com/l/licensekit-basic
gumroad-gold: https://danielsaidi.gumroad.com/l/licensekit-gold
twitter_url: https://twitter.com/getlicensekit
twitter_username: getlicensekit

assets: /assets/
header_icon: /assets/icon/icon-1024.png
header_icon_type: icon

header_pages:
  - index.html
  - pages/licenses.md
  - pages/blog.md

footer_pages_sitemap:
  - index.html
  - pages/blog.md

collections_dir: collections

collections:
  posts:
    output: true
    permalink: /blog/:categories/:year/:month/:day/:title
  sponsors:
    output: true
    permalink: /sponsor/:name/

baseurl: ""
theme: minima
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-redirect-from

defaults:
  -
    scope:
      type: "pages"
    values:
      hero: ""
  -
    scope:
      type: "posts"
    values:
      author: "danielsaidi"
      layout: "post"
      hero:   "none"
  -
    scope:
      type: "sponsors"
    values:
      layout: "sponsor"

include:
  - .well-known/

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/